spring:
  application:
    name: freelance-backend

  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/freelance_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

jwt:
  access:
    key: ${JWT_ACCESS_KEY:6aec213d794e0cbd15a0bd961b21b2e6d74376ad897f8423939278479b20c7fb}
    expiration-ms: ${JWT_ACCESS_EXPIRATION:604800000} # 7 days (change to 15 min 90000 ms)
  refresh:
    key: ${JWT_REFRESH_KEY:cde001b26cb22a86028a441d3c5b600a935a4606cd4b70aa03e5f679b5f2023d}
    expiration-ms: ${JWT_REFRESH_EXPIRATION:604800000} # 7 days
