spring:
  application:
    name: freelance-backend


  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

jwt:
  access:
    key: ${JWT_ACCESS_KEY}
    expiration-ms: ${JWT_ACCESS_EXPIRATION}
  refresh:
    key: ${JWT_REFRESH_KEY}
    expiration-ms: ${JWT_REFRESH_EXPIRATION}